# Generated by Django 4.2.3 on 2023-08-31 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='shop_app.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='shop_app.cart'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='deliverycrew',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(),
        ),
    ]
